server: 
        port: 9527
       
spring:
         application:
          name: api-zuul
         
eureka:
       client:
        service-url:
                      defaultZone:  http://localhost:7001/eureka/
zuul:  routes:    provider:
      path: /api/p/**    #**表示全路径匹配      service-id: provider    consumer:
      path: /api/c/**
      service-id: consumer
  LoginFilter:
           pre:
             disable: true  # 表示禁用过滤器LoginFilter

          