server: 
        port: 9001
       
spring:
         application:
          name: provider
eureka:
       client:
        service-url:
                      defaultZone:  http://localhost:7001/eureka/
       