  server:
          port: 8888
          
  spring:
        application:
          name: cloud-config
        cloud:
           config:
            label: master
            server:
               git:
                 uri: https://github.com/wuyuzhang97/cloud-config.git
                 username: wuyuzhang97 
                 password: wyz980107
  eureka:
       client:
        service-url:
                      defaultZone:  http://localhost:7001/eureka/