server: 
        port: 8081
       
spring:
         application:
          name: consumer
         
eureka:
       client:
        service-url:
                      defaultZone:  http://localhost:7001/eureka/

 